# CRIANDO BANCO DE DADOS
CREATE SCHEMA PROJETO_FORTES;

# SELECIONANDO BANCO DE DADOS
USE PROJETO_FORTES;

# CRIANDO TABELAS SEM CHAVE ESTRANGEIRA

# CRIANDO TABELA FUNCIONÁRIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    REGISTRO INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

# CRIANDO TABELA DONATÁRIOS
CREATE TABLE IF NOT EXISTS DONATARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

# CRIANDO TABELAS COM CHAVE ESTRANGEIRA

# CRIANDO TABELA EVENTOS
CREATE TABLE IF NOT EXISTS EVENTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    LOCAL_EVENTO VARCHAR(100)
    REGISTRO_FUNCIONARIO INT,
    ID_DONATARIO INT,
    FOREIGN KEY (REGISTRO_FUNCIONARIO) REFERENCES FUNCIONARIOS(REGISTRO),
    FOREIGN KEY (ID_DONATARIO) REFERENCES DONATARIOS(ID)
);

# CRIANDO TABELA EDITAIS
CREATE TABLE IF NOT EXISTS EDITAIS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(750),
    VALOR DECIMAL(20,2) NOT NULL,
    REGISTRO_FUNCIONARIO VARCHAR(100),
    FOREIGN KEY (REGISTRO_FUNCIONARIO) REFERENCES FUNCIONARIOS(REGISTRO)
);

# CRIANDO TABELA PROJETOS 
CREATE TABLE IF NOT EXISTS PROJETOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(750),
    ID_DONATARIO INT,
    ID_EDITAL INT,
    FOREIGN KEY (ID_DONATARIO) REFERENCES DONATARIOS(ID),
    FOREIGN KEY (ID_EDITAL) REFERENCES EDITAIS(ID)
);

# CRIANDO TABELA NOTAS FISCAIS
CREATE TABLE IF NOT EXISTS NOTAS_FISCAIS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(750) NOT NULL,
    VALOR DECIMAL(20,2) NOT NULL,
    ID_DONATARIO INT,
    FOREIGN KEY (ID_DONATARIO) REFERENCES DONATARIOS(ID) 
);
