CREATE SCHEMA EC3_SI1N;

USE EC3_SI1N;

#CIRANDO ENTIDADE FRACA TIPO DE TELEFONE
CREATE TABLE TIPO_TELEFONE (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

#CRIANDO ENTIDADE TELEFONES
CREATE TABLE TELEFONES (
    ID INT PRIMARY KEY,
    NUMERO VARCHAR(20) NOT NULL,
    TIPO_TEL_ID INT,
    EntidadeID INT NOT NULL,
    COD_CLIENTES INT,
    CNPJ_EMPRESA VARCHAR(18),
    CNPJ_FORNECEDOR VARCHAR(18),
    FOREIGN KEY (TIPO_TEL_ID) REFERENCES TIPO_TELEFONE(ID),
    FOREIGN KEY (CNPJ_EMPRESA) REFERENCES EMPRESAS(CNPJ),
    FOREIGN KEY (CNPJ_FONECEDOR) REFERENCES FORNECEDORES(CNPJ)
);

#CRIANDO ENTIDADE CLIENTES
CREATE TABLE CLIENTES (
    CODIGO INT PRIMARY KEY,
    RAZ_SOCIAL VARCHAR(100) NOT NULL,
    RAMO_ATIVIDADE VARCHAR(100),
    DATA_CADASTRO DATE,
    PESSOA_CONTATO VARCHAR(100),
    CNPJ_EMPRESA VARCHAR(18) NOT NULL,
    FOREIGN KEY (CNPJ_EMPRESA) REFERENCES EMPRESAS(CNPJ)
);

#CRIANDO ENTIDADE EMPREGADOS
CREATE TABLE EMPREGADOS (
    MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    SALARIO INT NOT NULL,
    DATA_ADMISSAO DATE,
    END_ID INT,
    FOREIGN KEY (END_ID) REFERENCES ENDERECOS(ID)
);

#CRIANDO ENTIDADE EMPRESAS
CREATE TABLE EMPRESAS (
    CNPJ VARCHAR(18) PRIMARY KEY,
    RAZ_SOCIAL VARCHAR(255) NOT NULL,
    PESSOA_CONTATO VARCHAR(255),
    END_ID INT,
    FOREIGN KEY (END_ID) REFERENCES ENDERECOS(ID)
);

#CRIANDO ENTIDADE FORNECEDORES
CREATE TABLE FORNECEDORES (
    CNPJ VARCHAR(18) PRIMARY KEY,
    RAZ_SOCIAL VARCHAR(255) NOT NULL,
    PESSOA_CONTATO VARCHAR(255),
    END_ID INT,
    FOREIGN KEY (END_ID) REFERENCES ENDERECOS(ID)
);

#CRIANDO ENTIDADE FRACA TIPO DE ENDEREÇO
CREATE TABLE TIPO_ENDERECOS (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

#CRIANDO ENTIDADE ENDEREÇOS
CREATE TABLE ENDERECOS (
    ID INT PRIMARY KEY,
    NOME VARCHAR(10),
    LOGRADOURO VARCHAR(255),
    COMPLEMENTO VARCHAR(100),
    CEP VARCHAR(10),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(2),
    TIPO_END_CODIGO INT,
    FOREIGN KEY (TIPO_END_CODIGO) REFERENCES TIPO_ENDEREÇOS(CODIGO)
);

#CRIANDO ENTIDADE ENCOMENDAS
CREATE TABLE ENCOMENDAS (
    NUMERO INT PRIMARY KEY,
    DATA_INCLUSAO DATE,
    VALOR_TOTAL DECIMAL(10, 2),
    VALOR_DESCONTOS DECIMAL(10, 2),
    VALOR_LIQUIDO DECIMAL(10, 2),
    FORMA_PAG_ID INT,
    QUANT_PARCELAS INT,
    COD_CLIENTES INT,
    FOREIGN KEY (COD_CLIENTES) REFERENCES CLIENTES(CODIGO)
);

#CRIANDO ENTIDADE PRODUTOS
CREATE TABLE PRODUTOS
(
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(255),
    COR VARCHAR(50),
    DIMENSOES VARCHAR(100),
    PESO DECIMAL(10, 2),
    PRECO DECIMAL(10, 2),
    TEMPO_FABRICACAO TIME,
    DESENHO_PRODUTO BLOB,
    MAO_OBRA DECIMAL(5, 2)
);

#CRIANDO ENTIDADE FRACA TIPOS DE COMPONENTE
CREATE TABLE TIPOS_COMPONENTES (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

#CRIANDO ENTIDADE COMPONENTES
CREATE TABLE COMPONENTES (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(255),
    QUANT_ESTOQUE INT,
    PRECO_UNIT DECIMAL(10, 2),
    UNIDADE VARCHAR(20),
    TIPO_COMP_CODIGO INT,
    FOREIGN KEY (TIPO_COMP_CODIGO) REFERENCES TIPOS_COMPONENTES(CODIGO)
);

#FORNECEDORES DE COMPONENTES
CREATE TABLE FORNECEDORES_COMPONENTES (
    COD_FORNECEDOR VARCHAR(18),
    COD_COMPONENTE INT,
    PRIMARY KEY (COD_FORNECEDOR, COD_COMPONENTE),
    FOREIGN KEY (CCOD_FORNECEDOR) REFERENCES FORNECEDORES(CNPJ),
    FOREIGN KEY (COD_COMPONENTE) REFERENCES COMPONENTES(CODIGO)
);

#CRIANDO ENTIDADE MÁQUINAS
CREATE TABLE MAQUINAS (
    ID INT PRIMARY KEY,
    TEMPO_VIDA INT,
    DATA_COMPRA DATE,
    DATA_FIM_GARANTIA DATE
);

#CRIANDO ENTIDADE RECURSOS ESPECÍFICOS
CREATE TABLE RECURSOS_ESPECIFICOS (
    ID INT PRIMARY KEY,
    QUANTIDADE_NECESSARIA DECIMAL(10, 2),
    UNIDADE VARCHAR(20),
    TEMPO_USO TIME,
    MAO_OBRA DECIMAL(5, 2)
);

#CRIANDO ENTIDADE REGISTRO DE MANUTENÇÃO
CREATE TABLE REGISTRO_MANUTENCAO (
    ID INT PRIMARY KEY,
    DATA_MANUTENCAO DATE,
    DESCRICAO TEXT,
    MAQUINA_ID INT,
    FOREIGN KEY (MAQUINA_ID) REFERENCES MAQUINAS(ID)
);

#CRIANDO ENTIDADE REGISTRO DE SUPRIMENTOS
CREATE TABLE REGISTRO_SUPRIMENTOS (
    ID INT PRIMARY KEY,
    QUANTIDADE DECIMAL(10, 2),
    DATA_NECESSIDADE DATE,
    COMP_ID INT,
    FOREIGN KEY (COMP_ID) REFERENCES COMPONENTES(CODIGO)
);
