DROP SCHEMA IF EXISTS EST_CASOV;
CREATE SCHEMA EST_CASOV;
USE EST_CASOV;

CREATE TABLE IF NOT EXISTS CLIENTES (
    CPF_CLI CHAR(14) PRIMARY KEY,
    NOME_CLI VARCHAR(45) NOT NULL,
    NASC_CLI DATE,
    STATUS_CLI ENUM('SIM', 'NÃO') DEFAULT 'NÃO',
    CIDADE_CLI VARCHAR(50),
    ESTADO_CLI VARCHAR(50),
    PAIS_CLI VARCHAR(50),
    TELEFONE_CLI VARCHAR(12),
    ENDERECO_CLI VARCHAR(100),
    BAIRRO_CLI VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(70) NOT NULL,
    DIMENSOES_PRODUTO INT NOT NULL,
    VALOR_PRODUTO DECIMAL(12, 2) NOT NULL,
    DESCRICAO_PRODUTO TEXT,
    COR_PRODUTO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    ID_FORN INT PRIMARY KEY,
    CNPJ CHAR(11) NOT NULL,
    ENDERECO_FORN VARCHAR(100),
    EMAIL_FORN VARCHAR(50),
    TELEFONE_FORN VARCHAR(12),
    CONTATO_FORN VARCHAR(100) NOT NULL,
    PRODUTO_FORN VARCHAR(30) NOT NULL,
    DESCRICAO_PRODUTO_FORN VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
    ID_ESTOQUE INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    LOC_PROD_ESTOQUE VARCHAR(100) NOT NULL,
    DATA_RECEBIMENTO DATE,
    ID_PRODUTO INT,
    CONSTRAINT FK_PRODUTO_E_ESTOQUE FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS VENDA (
    ID_VENDA INT PRIMARY KEY,
    PRODUTO_VENDA INT NOT NULL,
    QNT_PRODUTO_VENDA INT NOT NULL,
    ID_CLIENTE CHAR(14),
    DATA_VENDA DATE,
    VALOR_TOTAL DECIMAL(12, 2),
    CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CPF_CLI),
    CONSTRAINT FK_PRODUTO_VENDA FOREIGN KEY (PRODUTO_VENDA) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    ID_PAGAMENTO INT PRIMARY KEY,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGAMENTO DECIMAL(12, 2) NOT NULL,
    SITUACAO_PAGAMENTO ENUM('PAGO', 'PENDENTE') DEFAULT 'PENDENTE',
    ID_CLIENTE CHAR(14) NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CPF_CLI)
);

CREATE TABLE IF NOT EXISTS CLIENTES_PRODUTOS (
    ID_CLPR INT PRIMARY KEY AUTO_INCREMENT,
    CPF_CLI CHAR(14) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    CONSTRAINT FK_E_CLIENTE FOREIGN KEY (CPF_CLI) REFERENCES CLIENTES(CPF_CLI),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS VENDA_PRODUTOS (
    ID_VENDA INT,
    ID_PRODUTO INT,
    QNT_PRODUTO INT NOT NULL,
    PRIMARY KEY (ID_VENDA, ID_PRODUTO),
    CONSTRAINT FK_E_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA),
    CONSTRAINT FK_E_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

-- BEGIN ALTER TABLES! <3
ALTER TABLE CLIENTES 
DROP COLUMN IF EXISTS PRIMARIA;

ALTER TABLE PRODUTOS 
DROP COLUMN IF EXISTS DISP_PRODUTO;

ALTER TABLE FORNECEDORES 
DROP COLUMN IF EXISTS TELEFONE_FORN;

ALTER TABLE ESTOQUE 
DROP COLUMN IF EXISTS QNT_PROD_ESTOQUE;

ALTER TABLE VENDA 
DROP COLUMN IF EXISTS PAGAMENTO_VENDA;

ALTER TABLE PAGAMENTOS 
DROP COLUMN IF EXISTS CLIENTE_PAGAMENTO;

